---
title: "Using Postgre with R"
output: html_notebook
---


```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(lubridate) 
library(kableExtra)
options(knitr.table.format = "html")
library(streamgraph)
library(viridis)
library(DT)
library(plotly)
library(nlme)
```

```{r}

Q2b_Data <- read_csv('../data/data-1741913998693_GroupedByDate_n_PartID.csv')

Q2b_Data <- Q2b_Data |> unite("PartID_LongDescription", jmp_part_id:jmp_part_long_description_text, sep = " Description: ", remove = FALSE)

Q2b_Data

```

```{r}
Q2b_Data <- Q2b_Data |> 
                mutate(Production_Due_Date_DateTimeFormat = as_datetime(Q2b_Data$jmp_production_due_date, tz = "US/Eastern", format = NULL)) |>   
                select(jmp_part_id, PartID_LongDescription, total_quantity_for_manufactured_part, Production_Due_Date_DateTimeFormat) |> arrange(Production_Due_Date_DateTimeFormat, jmp_part_id)

Q2b_Data

```

```{r} 

Top12_Highly_InDemand_Parts_ID_n_LongDescription <- Q2b_Data |> 
                                group_by(PartID_LongDescription) |> 
                                summarise(Sum_of_Total_Quantity_for_Manufactured_Part = sum(total_quantity_for_manufactured_part)) |> 
                                arrange(desc(Sum_of_Total_Quantity_for_Manufactured_Part)) |> 
                                head(12) |> 
                                pull(PartID_LongDescription)

Top12_Highly_InDemand_Parts_ID_n_LongDescription

# Q2b_Data <- Q2b_Data |>
#               mutate(Production_Due_Date_DateFormat = as.datetime(Production_Due_Date_DateTimeFormat))
# Q2b_Data


```

```{r}
Top12_Highly_InDemand_Parts_ID_n_LongDescription_tibble <- tibble(Top12_Highly_InDemand_Parts_ID_n_LongDescription)
Top12_Highly_InDemand_Parts_ID_n_LongDescription_tibble
```

```{r}

Top12_Highly_InDemand_Parts_data <- Q2b_Data |> filter(PartID_LongDescription %in% c(Top12_Highly_InDemand_Parts_ID_n_LongDescription))  

Top12_Highly_InDemand_Parts_data

```




```{r}
Top12_Highly_InDemand_Parts_data |>
  ggplot( aes(x = Production_Due_Date_DateTimeFormat, y = total_quantity_for_manufactured_part, group=jmp_part_id, color=jmp_part_id)) +
      geom_point() +
      scale_color_viridis(discrete = TRUE) +
      theme(
        legend.position = "none",
        plot.title = element_text(size = 14)
      ) +
      ggtitle("1st exploratory graph") +
      theme_ipsum()
```
```{r}


Q2b_Data |> 
  mutate( highlight=ifelse(jmp_part_id=="S038-0163", "S038-0163", "Other" )) |> 
  arrange(Production_Due_Date_DateTimeFormat) |> 
  filter(jmp_part_id=="S038-0163") |> 
  ggplot( aes(x=Production_Due_Date_DateTimeFormat, y=total_quantity_for_manufactured_part, group=jmp_part_id, color=highlight, linewidth=highlight)) +
    geom_line() +
    scale_color_manual(values = c("#69b3a2", "lightgrey")) +
    scale_size_manual(values=c(1.5,0.2)) +
    theme(legend.position="none") +
  #  ggtitle("Popularity of American names in the previous 30 years") +
    theme_ipsum() +
   # geom_label( x=1990, y=55000, label="Amanda reached 3550\nbabies in 1970", size=4, color="#69b3a2") +
    theme(
      legend.position="none",
      plot.title = element_text(size=14)
)

```


```{r}

Top12_Highly_InDemand_Parts_data |>  distinct(Production_Due_Date_DateTimeFormat) |> arrange(Production_Due_Date_DateTimeFormat)


```

```{r}

YMD_series <- tibble(date = seq(ymd('2022-02-08'), ymd('2025-02-25'), by='1 day'))
YMD_series


```
```{r}

CrossJoined_YMDseries_Top12Parts <- cross_join(YMD_series, Top12_Highly_InDemand_Parts_ID_n_LongDescription_tibble) |> 
                                      rename(Production_Due_Date_DateTimeFormat = date, PartID_LongDescription = Top12_Highly_InDemand_Parts_ID_n_LongDescription)

CrossJoined_YMDseries_Top12Parts

```

```{r}

LeftJoined_YMDseries_Top12Parts <- left_join(CrossJoined_YMDseries_Top12Parts, Top12_Highly_InDemand_Parts_data, by = c('Production_Due_Date_DateTimeFormat', 'PartID_LongDescription')) |>
                                    replace_na(list(total_quantity_for_manufactured_part = 0))  |>  
                                    arrange(Production_Due_Date_DateTimeFormat)  

LeftJoined_YMDseries_Top12Parts

```

```{r}

LeftJoined_YMDseries_Top12Parts_withDescription <- left_join(LeftJoined_YMDseries_Top12Parts, Top12_Highly_InDemand_Parts_data, by = c('Production_Due_Date_DateTimeFormat', 'PartID_LongDescription'))
LeftJoined_YMDseries_Top12Parts_withDescription


```


```{r}

LeftJoined_YMDseries_Top12Parts <- LeftJoined_YMDseries_Top12Parts |>
    mutate(PartID_LongDescription2 = PartID_LongDescription)


LeftJoined_YMDseries_Top12Parts |>
  ggplot( aes(x=Production_Due_Date_DateTimeFormat, y=total_quantity_for_manufactured_part)) +
      geom_line(data = LeftJoined_YMDseries_Top12Parts |> dplyr::select(-PartID_LongDescription), aes(group=PartID_LongDescription2), color="grey", linewidth=0.5, alpha=0.5) +
      geom_point( aes(color=PartID_LongDescription), color="#69b3a2" ) +
      geom_line( aes(color=PartID_LongDescription), color="#69b3a2", linewidth=0.15 ) +
      scale_color_viridis(discrete = TRUE) +
      theme_ipsum() +
      theme(
        legend.position="none",
        plot.title = element_text(size=14),
        panel.grid = element_blank()
      ) +
      ggtitle("Quantity of Parts Ordered Over Time") +
      facet_wrap(~PartID_LongDescription)

```
